export const subsidyCSVRow = {
  year: "id",
  organizationNumber: "id", 
  organization: "name",
  policyFieldNumber: "id",
  policyField: "name",
  businessName: "name",
  subsidyName: "name",
  subsidyDescription: "summary",
  targetNumber: "id",
  target: "summary",
  budgetAmount: "summary",
  department: "summary",
  contact: "summary",
  url: "summary",
} as const;
